name: holon_basic_recipes_workflow

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    timeout-minutes: 30
    runs-on: ubuntu-latest
    continue-on-error: true

    steps:
    - name: Checkout current repository
      uses: actions/checkout@v4
      
    - name: Common CI Setup
      uses: ./.github/actions/common-ci-setup

    - name: Copy run-recipes.sh and basic_recipes.txt
      run: |
        cp ./scripts/run-recipes.sh /home/runner/work/niovad/niovad/build_dir/
        cp ./scripts/basic_recipes.txt /home/runner/work/niovad/niovad/build_dir/
      shell: bash

    - name: Checkout holon repo
      uses: actions/checkout@v4
      with:
        repository: 00pauln00/holon
        ref: niova_core_recipes_compatibility
        path: ./holon

    - name: Copy holon repo to build_dir
      run: cp -r ./holon /home/runner/work/niovad/niovad/build_dir/
      shell: bash

    - name: Create log directory
      run: mkdir -p /home/runner/work/niovad/niovad/holon_log
      shell: bash

    - name: Run holon basic recipes
      run: |
        cd /home/runner/work/niovad/niovad/build_dir/holon/
        ../run-recipes.sh \
          "/home/runner/work/niovad/niovad/build_dir/holon" \
          "/home/runner/work/niovad/niovad/build_dir" \
          "/home/runner/work/niovad/niovad/holon_log" 5 \
          "/home/runner/work/niovad/niovad/build_dir/basic_recipes.txt" \
          "raft" \
          "/home/runner/work/go/go/bin"
      shell: bash

    - name: Prepare artifact filename
      id: prepare_artifact_filename
      if: failure()
      run: echo "ARTIFACT_NAME=test-recipe-report_${{ github.event.pull_request.head.sha }}_${{ github.run_attempt }}" >> "$GITHUB_OUTPUT"
      shell: bash

    - name: Archive the test results
      if: failure()
      uses: actions/upload-artifact@v4
      with:
        name: ${{ steps.prepare_artifact_filename.outputs.ARTIFACT_NAME }}
        path: /home/runner/work/niovad/niovad/holon_log
