name: holon_basic_recipes_workflow

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    timeout-minutes: 30
    runs-on: ubuntu-latest
    continue-on-error: true

    steps:
    - name: Checkout current repository
      uses: actions/checkout@v4

    - name: Common CI Setup
      uses: ./.github/actions/common-setup

    - name: Copy run-recipes.sh and basic_recipes.txt
      run: |
        cp ./scripts/run-recipes.sh /home/runner/work/niovad/niovad/build_dir/
        cp ./scripts/basic_recipes.txt /home/runner/work/niovad/niovad/build_dir/
      shell: bash

    - name: Checkout holon repo
      uses: actions/checkout@v4
      with:
        repository: 00pauln00/holon
        ref: raft_recipes_fix
        path: ./holon

    - name: Copy holon repo to build_dir
      run: cp -r ./holon /home/runner/work/niovad/niovad/build_dir/
      shell: bash

    - name: Create log directory
      run: mkdir -p /home/runner/work/niovad/niovad/holon_log
      shell: bash

    - name: Run holon basic recipes
      run: |
        cd /home/runner/work/niovad/niovad/build_dir/holon/
        ../run-recipes.sh \
          "/home/runner/work/niovad/niovad/build_dir/holon" \
          "/home/runner/work/niovad/niovad/build_dir" \
          "/home/runner/work/niovad/niovad/holon_log" 5 \
          "/home/runner/work/niovad/niovad/build_dir/basic_recipes.txt" \
          "raft" \
          "/home/runner/work/go/go/bin"
      shell: bash

    - name: Teardown and archive on failure
      if: failure()
      uses: ./.github/actions/teardown-failure